name: "Code Style Validation"

env:
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  validate_style:
    name: Validate Code Style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Add private NuGet source
      run: |
        dotnet nuget add source https://gitlab.com/api/v4/projects/63188031/packages/nuget/index.json \
          --name GitLab \
          --username $NUGET_USERNAME \
          --password $NUGET_PASSWORD \
          --store-password-in-clear-text

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Validate code style
      run: |
        dotnet format --verify-no-changes --check ./TelegramBotService/TelegramBotService.sln
        dotnet format --verify-no-changes --check ./NotificationService/NotificationService.sln
        dotnet format --verify-no-changes --check ./FileService/FileService.sln
        dotnet format --verify-no-changes --check ./CacheInvalidatorService/CacheInvalidatorService.sln
        dotnet format --verify-no-changes --check ./backend/backend.sln
